### PR TITLE
Rspec for controller admin user_bets

### PR DESCRIPTION
**Pull request by binhpt-1239**
Related Tickets
• [#48008](https://edu-redmine.sun-asterisk.vn/issues/48008)

WHAT
- Write Rspec for controller admin user_bets

HOW
- Write shared_example
- Write Rspec for controller admin user_bets
- modify flash in base_controller

Screenshot from 2022-04-07 00-10-46
Screenshot from 2022-04-07 00-09-53

### CODE REVIEW

**Comment by binhpt-1239** [comment]
ready

**Comment by BaoKhanh99** [comment]
ok

**Comment by binhpt-1239** [comment]
ready

**Comment by binhpt-1239** [comment]
ready

**Pull request merged**
