### PR TITLE
Modify file Seed and models

### PR DESCRIPTION
**Pull request by binhpt-1239**
Related Tickets
• [#47137](https://edu-redmine.sun-asterisk.vn/issues/47133)
What
- Modify file Seed and models

How
- Add seed data soccer match, Bet
- modify table CSDL
- modify model

Screenshot from 2022-03-22 17-56-28

### CODE REVIEW

**Comment by binhpt-1239** [comment]
ready

**Comment by BaoKhanh99** [comment]
Ok

**Comment by nvatuan** [comment]
Ok

**Review by huongnt-2545 — APPROVED** [review]
merged

**Pull request merged**
